on: push
name: Test apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.3'
    - run: flutter pub get
    - run: flutter build apk --debug
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: test.apk
        path: ./build/app/outputs/apk/debug
